name: Build Kokoro EN-only (FP32 & Q8)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: [fp32, q8]
    env:
      APP_DIR: android/SherpaOnnxTtsEngine
      ASSETS_DIR: android/SherpaOnnxTtsEngine/app/src/main/assets/model
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install platform, build-tools, NDK, CMake + accept licenses
        shell: bash
        run: |
          set -euxo pipefail
          # Accept licenses but don't fail on SIGPIPE from `yes`
          yes | sdkmanager --licenses >/dev/null 2>&1 || true
          sdkmanager --install \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0" \
            "ndk;26.3.11579264" \
            "cmake;3.22.1"
          echo "NDK path:"; ls -al "$ANDROID_SDK_ROOT/ndk" || true

      - name: Prepare English-only assets from official EN APK (voices/tokens/lexicons)
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p "$ASSETS_DIR"
          curl -fL --retry 3 --retry-delay 5 \
            -H "Accept: application/octet-stream" \
            -o en.apk \
            "https://huggingface.co/csukuangfj/sherpa-onnx-apk/resolve/main/tts-engine-new/1.12.14/sherpa-onnx-1.12.14-arm64-v8a-en-tts-engine-kokoro-en-v0_19.apk"
          unzip -Z1 en.apk | sed -n '/^assets\/model\//p'
          unzip -j en.apk "assets/model/*" -d "$ASSETS_DIR"
          ls -lah "$ASSETS_DIR"
          cd "$ASSETS_DIR"
          [ -f tokens.txt ] || mv tokens* tokens.txt 2>/dev/null || true
          [ -f voices.bin ] || mv voices* voices.bin 2>/dev/null || true
          cd -

      - name: Swap ONNX model (FP32 or Q8)
        shell: bash
        run: |
          set -euxo pipefail
          cd "$ASSETS_DIR"
          rm -f model.onnx || true
          if [ "${{ matrix.profile }}" = "fp32" ]; then
            MODEL_URL="https://huggingface.co/onnx-community/Kokoro-82M-v1.0-ONNX/resolve/main/onnx/model.onnx"
          else
            MODEL_URL="https://huggingface.co/onnx-community/Kokoro-82M-v1.0-ONNX/resolve/main/onnx/model_quantized.onnx"
            # To try Q8F16 instead: MODEL_URL="https://huggingface.co/onnx-community/Kokoro-82M-v1.0-ONNX/resolve/main/onnx/model_q8f16.onnx"
          fi
          curl -fL --retry 3 --retry-delay 5 \
            -H "Accept: application/octet-stream" \
            -o model.onnx \
            "$MODEL_URL"
          echo "Final files in assets/model:"; ls -lah .
          # Sanity check to fail fast if anything's missing
          test -f model.onnx && test -f tokens.txt && test -f voices.bin

      - name: Make Gradle wrapper executable
        run: chmod +x $APP_DIR/gradlew

      - name: Assemble Release (arm64-v8a)
        working-directory: ${{ env.APP_DIR }}
        env:
          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/26.3.11579264
        run: ./gradlew --no-daemon assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kokoro-en-${{ matrix.profile }}
          path: android/SherpaOnnxTtsEngine/app/build/outputs/apk/release/*.apk
