name: Build Kokoro EN-only (FP32 & Q8)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: [fp32, q8]   # build both variants
    env:
      APP_DIR: android/SherpaOnnxTtsEngine
      ASSETS_DIR: android/SherpaOnnxTtsEngine/app/src/main/assets/model
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install platform, build-tools, NDK, CMake + accept licenses
        shell: bash
        run: |
          set -euxo pipefail
          # Be tolerant of SIGPIPE from `yes`
          yes | sdkmanager --licenses >/dev/null 2>&1 || true
          sdkmanager --install \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;34.0.0" \
            "ndk;26.3.11579264" \
            "cmake;3.22.1"
          echo "Installed NDKs:"; ls -al "$ANDROID_SDK_ROOT/ndk" || true

      - name: Prepare English-only assets from official EN APK (voices/tokens/lexicons)
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p "$ASSETS_DIR"

          # Download the official English-only TTS Engine APK
          curl -fL --retry 3 --retry-delay 5 \
            -H "Accept: application/octet-stream" \
            -o en.apk \
            "https://huggingface.co/csukuangfj/sherpa-onnx-apk/resolve/main/tts-engine-new/1.12.14/sherpa-onnx-1.12.14-arm64-v8a-en-tts-engine-kokoro-en-v0_19.apk"

          # Extract ALL assets to a temp dir (APK layout can change)
          TMP_ASSETS="$(mktemp -d)"
          unzip -q en.apk -d "$TMP_ASSETS"

          echo "APK assets (first 200 lines):"
          find "$TMP_ASSETS/assets" -type f | sed 's/^/  /' | head -n 200 || true

          # Copy required files into a flat assets/model/ folder
          find "$TMP_ASSETS" -iname 'tokens.txt' -exec cp -v {} "$ASSETS_DIR/tokens.txt" \; || true
          find "$TMP_ASSETS" -iname 'voices.bin' -exec cp -v {} "$ASSETS_DIR/voices.bin" \; || true
          find "$TMP_ASSETS" -iname 'lexicon-us-en.txt' -exec cp -v {} "$ASSETS_DIR/lexicon-us-en.txt" \; || true
          find "$TMP_ASSETS" -iname 'lexicon-gb-en.txt' -exec cp -v {} "$ASSETS_DIR/lexicon-gb-en.txt" \; || true

          echo "Final files in $ASSETS_DIR:"
          ls -lah "$ASSETS_DIR"

          # Fail fast if core files are missing
          test -f "$ASSETS_DIR/tokens.txt"
          test -f "$ASSETS_DIR/voices.bin"

      - name: Swap ONNX model (FP32 or Q8)
        shell: bash
        run: |
          set -euxo pipefail
          cd "$ASSETS_DIR"
          rm -f model.onnx || true

          if [ "${{ matrix.profile }}" = "fp32" ]; then
            MODEL_URL="https://huggingface.co/onnx-community/Kokoro-82M-v1.0-ONNX/resolve/main/onnx/model.onnx"
          else
            MODEL_URL="https://huggingface.co/onnx-community/Kokoro-82M-v1.0-ONNX/resolve/main/onnx/model_quantized.onnx"
            # Prefer Q8F16 instead? Use:
            # MODEL_URL="https://huggingface.co/onnx-community/Kokoro-82M-v1.0-ONNX/resolve/main/onnx/model_q8f16.onnx"
          fi

          curl -fL --retry 3 --retry-delay 5 \
            -H "Accept: application/octet-stream" \
            -o model.onnx \
            "$MODEL_URL"

          echo "Final files in assets/model:"
          ls -lah .

          # Sanity check
          test -f model.onnx && test -f tokens.txt && test -f voices.bin

      - name: Make Gradle wrapper executable
        run: chmod +x $APP_DIR/gradlew

      - name: Assemble Release (arm64-v8a)
        working-directory: ${{ env.APP_DIR }}
        env:
          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/26.3.11579264
          ORG_GRADLE_PROJECT_org_gradle_logging_stacktrace: all
        run: ./gradlew --no-daemon assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kokoro-en-${{ matrix.profile }}
          path: android/SherpaOnnxTtsEngine/app/build/outputs/apk/release/*.apk
```0
