name: Build English-only Kokoro Q8F16 (Debug)

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_DIR: android/SherpaOnnxTtsEngine
      ASSETS_DIR: android/SherpaOnnxTtsEngine/app/src/main/assets/model
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK (install packages & accept licenses)
        uses: android-actions/setup-android@v3
        with:
          accept-android-sdk-licenses: true
          log-accepted-android-sdk-licenses: true
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0
            ndk;26.3.11579264
            cmake;3.22.1

      - name: Extract EN-only assets from official APK (voices/tokens/lexicons)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$ASSETS_DIR"
          curl -fL --retry 3 --retry-delay 5 \
            -H "Accept: application/octet-stream" \
            -o en.apk \
            "https://huggingface.co/csukuangfj/sherpa-onnx-apk/resolve/main/tts-engine-new/1.12.14/sherpa-onnx-1.12.14-arm64-v8a-en-tts-engine-kokoro-en-v0_19.apk"
          TMP_ASSETS="$(mktemp -d)"
          unzip -q en.apk -d "$TMP_ASSETS"
          # Copy the assets we need into our project
          find "$TMP_ASSETS" -iname 'tokens.txt' -exec cp -v {} "$ASSETS_DIR/tokens.txt" \; || true
          find "$TMP_ASSETS" -iname 'voices.bin' -exec cp -v {} "$ASSETS_DIR/voices.bin" \; || true
          find "$TMP_ASSETS" -iname 'lexicon-us-en.txt' -exec cp -v {} "$ASSETS_DIR/lexicon-us-en.txt" \; || true
          find "$TMP_ASSETS" -iname 'lexicon-gb-en.txt' -exec cp -v {} "$ASSETS_DIR/lexicon-gb-en.txt" \; || true
          # Sanity: required files
          test -f "$ASSETS_DIR/tokens.txt"
          test -f "$ASSETS_DIR/voices.bin"

      - name: Swap ONNX to Kokoro v1.0 Q8F16 (best quality @ speed)
        shell: bash
        run: |
          set -euo pipefail
          cd "$ASSETS_DIR"
          rm -f model.onnx || true
          curl -fL --retry 3 --retry-delay 5 \
            -H "Accept: application/octet-stream" \
            -o model.onnx \
            "https://huggingface.co/onnx-community/Kokoro-82M-v1.0-ONNX/resolve/main/onnx/model_q8f16.onnx"
          ls -lah .
          # Sanity
          test -f model.onnx && test -f tokens.txt && test -f voices.bin

      - name: Make Gradle wrapper executable
        run: chmod +x $APP_DIR/gradlew

      - name: Assemble Debug (arm64-v8a)
        working-directory: ${{ env.APP_DIR }}
        env:
          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/26.3.11579264
        run: |
          set -euo pipefail
          ./gradlew --no-daemon --stacktrace --warning-mode all assembleDebug

      - name: Show packaged assets in debug APK
        if: always()
        shell: bash
        run: |
          set -euo pipefail
          APK="${{ env.APP_DIR }}/app/build/outputs/apk/debug/app-debug.apk"
          unzip -Z1 "$APK" | sed -n '/^assets\/model\//p' || true

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: sherpa-onnx-tts-engine-english-q8f16-debug
          path: android/SherpaOnnxTtsEngine/app/build/outputs/apk/debug/app-debug.apk
