name: Build Kokoro EN-only (FP32 & Q8)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: [fp32, q8]

    env:
      APP_DIR: android/SherpaOnnxTtsEngine
      ASSETS_DIR: android/SherpaOnnxTtsEngine/app/src/main/assets/model
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # ⬇️ Let the action install everything and accept licenses
      - name: Set up Android SDK + packages
        uses: android-actions/setup-android@v3
        with:
          # Pin to a stable cmdline-tools to avoid version mismatch warnings
          cmdline-tools-version: 12266719
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0
            ndk;26.3.11579264
            cmake;3.22.1

      - name: Prepare English assets
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p "$ASSETS_DIR"
          curl -fL --retry 3 --retry-delay 5 -H "Accept: application/octet-stream" -o en.apk \
            "https://huggingface.co/csukuangfj/sherpa-onnx-apk/resolve/main/tts-engine-new/1.12.14/sherpa-onnx-1.12.14-arm64-v8a-en-tts-engine-kokoro-en-v0_19.apk"
          TMP_ASSETS="$(mktemp -d)"
          unzip -q en.apk -d "$TMP_ASSETS"
          # copy only what we need
          find "$TMP_ASSETS" -iname 'tokens.txt' -print -quit | xargs -rI{} cp -v "{}" "$ASSETS_DIR/tokens.txt"
          find "$TMP_ASSETS" -iname 'voices.bin' -print -quit | xargs -rI{} cp -v "{}" "$ASSETS_DIR/voices.bin"
          find "$TMP_ASSETS" -iname 'lexicon-us-en.txt' -print -quit | xargs -rI{} cp -v "{}" "$ASSETS_DIR/lexicon-us-en.txt" || true
          find "$TMP_ASSETS" -iname 'lexicon-gb-en.txt' -print -quit | xargs -rI{} cp -v "{}" "$ASSETS_DIR/lexicon-gb-en.txt" || true
          test -f "$ASSETS_DIR/tokens.txt"
          test -f "$ASSETS_DIR/voices.bin"

      - name: Swap ONNX model (fp32 vs q8)
        shell: bash
        run: |
          set -euxo pipefail
          cd "$ASSETS_DIR"
          rm -f model.onnx || true
          if [ "${{ matrix.profile }}" = "fp32" ]; then
            MODEL_URL="https://huggingface.co/onnx-community/Kokoro-82M-v1.0-ONNX/resolve/main/onnx/model.onnx"
          else
            MODEL_URL="https://huggingface.co/onnx-community/Kokoro-82M-v1.0-ONNX/resolve/main/onnx/model_quantized.onnx"
          fi
          curl -fL --retry 3 --retry-delay 5 -H "Accept: application/octet-stream" -o model.onnx "$MODEL_URL"
          test -f model.onnx

      - name: Locate Gradle wrapper
        id: gw
        shell: bash
        run: |
          set -euo pipefail
          if [ -x "${APP_DIR}/gradlew" ]; then
            echo "wrapper=${APP_DIR}/gradlew" >> "$GITHUB_OUTPUT"
          elif [ -x "./gradlew" ]; then
            echo "wrapper=./gradlew" >> "$GITHUB_OUTPUT"
          else
            echo "Gradle wrapper not found in ${APP_DIR} or repo root."
            ls -la "${APP_DIR}" || true
            exit 1
          fi

      - name: Make Gradle wrapper executable & show version
        shell: bash
        run: |
          set -euxo pipefail
          chmod +x "${{ steps.gw.outputs.wrapper }}"
          "${{ steps.gw.outputs.wrapper }}" --version

      - name: Assemble Debug
        working-directory: ${{ env.APP_DIR }}
        env:
          ANDROID_NDK_HOME: /usr/local/lib/android/sdk/ndk/26.3.11579264
        run: ${{ steps.gw.outputs.wrapper }} --no-daemon assembleDebug

      - name: Show packaged assets (debug APK)
        shell: bash
        run: |
          set -euxo pipefail
          APK="${{ env.APP_DIR }}/app/build/outputs/apk/debug/app-debug.apk"
          unzip -Z1 "$APK" | sed -n '/^assets\/model\//p' || true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kokoro-en-${{ matrix.profile }}-debug
          path: android/SherpaOnnxTtsEngine/app/build/outputs/apk/debug/app-debug.apk
